# Generated by Django 5.0.1 on 2025-12-12 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentparent",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentparent",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parents",
                to="students.student",
            ),
        ),
        migrations.AddIndex(
            model_name="classgroup",
            index=models.Index(
                fields=["school", "academic_year"],
                name="class_group_school__a67b62_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="classgroup",
            index=models.Index(
                fields=["grade_level"], name="class_group_grade_l_0a0937_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="classgroup",
            unique_together={("school", "name", "academic_year")},
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["school", "class_group"], name="students_school__2aabbb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["student_number"], name="students_student_fa2474_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentparent",
            unique_together={("student", "parent")},
        ),
    ]
