# Generated by Django 5.0.1 on 2025-12-12 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schedule", "0001_initial"),
        ("schools", "0001_initial"),
        ("staff", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="class_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="students.classgroup",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="schools.school",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="staff.subject",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="staff.staff",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="schedule.course",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="staff.staff",
            ),
        ),
        migrations.AddField(
            model_name="scheduleslot",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule_slots",
                to="schedule.course",
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["school", "academic_year"], name="courses_school__4e5032_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["teacher"], name="courses_teacher_e891c2_idx"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["class_group"], name="courses_class_g_626a35_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["course", "date"], name="lessons_course__5ab74a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["teacher", "date"], name="lessons_teacher_13c796_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(fields=["date"], name="lessons_date_53c4c2_idx"),
        ),
        migrations.AddIndex(
            model_name="scheduleslot",
            index=models.Index(
                fields=["course", "day_of_week"], name="schedule_sl_course__7b0640_idx"
            ),
        ),
    ]
