# Generated by Django 5.0.1 on 2025-12-12 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("journal", "0001_initial"),
        ("schedule", "0002_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="from_user",
            field=models.ForeignKey(
                help_text="Учитель, оставивший фидбэк",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback_given",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="to_student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedback_received",
                to="students.student",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to="schedule.course",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                help_text="Оценка за конкретный урок (опционально)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to="schedule.lesson",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="recorded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grades_recorded",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to="students.student",
            ),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["to_student", "date"], name="feedback_to_stud_43d6d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(
                fields=["from_user"], name="feedback_from_us_b44624_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(
                fields=["student", "course"], name="grades_student_c6f53c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(
                fields=["student", "date"], name="grades_student_e66109_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(
                fields=["course", "date"], name="grades_course__65e9b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grade",
            index=models.Index(fields=["type"], name="grades_type_aa7fa1_idx"),
        ),
    ]
