# Generated by Django 5.0.1 on 2025-12-12 19:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("nis", "НИШ"),
                            ("ktl", "КТЛ"),
                            ("haileybury", "Haileybury"),
                            ("fmsh", "ФМШ"),
                            ("others", "Другие"),
                        ],
                        default="others",
                        max_length=20,
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("address", models.TextField(blank=True)),
                (
                    "grading_system",
                    models.JSONField(
                        default=dict,
                        help_text="Настройки шкалы оценок, например: {'scale': '10-point', 'min': 0, 'max': 10}",
                    ),
                ),
                (
                    "languages_supported",
                    models.JSONField(
                        default=list,
                        help_text="Список поддерживаемых языков: ['ru', 'kz', 'en']",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "School",
                "verbose_name_plural": "Schools",
                "db_table": "schools",
                "indexes": [
                    models.Index(fields=["type"], name="schools_type_80863a_idx"),
                    models.Index(fields=["city"], name="schools_city_63b57a_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="e.g., '2024-2025'", max_length=50),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_current", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_years",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Academic Year",
                "verbose_name_plural": "Academic Years",
                "db_table": "academic_years",
                "indexes": [
                    models.Index(
                        fields=["school", "is_current"],
                        name="academic_ye_school__c0cb28_idx",
                    )
                ],
                "unique_together": {("school", "name")},
            },
        ),
    ]
