# Generated by Django 5.0.1 on 2025-12-12 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attendance", "0001_initial"),
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="schedule.lesson",
            ),
        ),
    ]
