# Generated by Django 5.0.1 on 2025-12-12 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0001_initial"),
        ("staff", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="staffsubject",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="staff.staff",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="schools.school",
            ),
        ),
        migrations.AddField(
            model_name="staffsubject",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_members",
                to="staff.subject",
            ),
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(
                fields=["school", "position"], name="staff_school__920862_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(fields=["school"], name="subjects_school__01dc27_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together={("school", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="staffsubject",
            unique_together={("staff", "subject")},
        ),
    ]
