# Generated by Django 5.0.1 on 2025-12-12 19:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("issue_date", models.DateField()),
                ("expires", models.DateField(blank=True, null=True)),
                (
                    "pdf_url",
                    models.URLField(blank=True, help_text="URL для скачивания PDF"),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        help_text="Файл сертификата",
                        null=True,
                        upload_to="certificates/",
                    ),
                ),
                (
                    "template_id",
                    models.CharField(
                        blank=True, help_text="ID шаблона сертификата", max_length=100
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="ru",
                        help_text="Язык сертификата (ru/kz/en)",
                        max_length=2,
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        default=dict,
                        help_text="Дополнительные данные (подписи, печати, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Certificate",
                "verbose_name_plural": "Certificates",
                "db_table": "certificates",
            },
        ),
        migrations.CreateModel(
            name="CertificateTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "html_template",
                    models.TextField(
                        help_text="HTML шаблон с placeholders ({{student_name}}, {{grade}}, etc.)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Certificate Template",
                "verbose_name_plural": "Certificate Templates",
                "db_table": "certificate_templates",
            },
        ),
    ]
